### ISSUE TITLE
enabling this extension crashes forum (twig can't get name of {%- EVENT 'marttiphpbb_jqueryuidatepicker' -%} )

### ISSUE THREAD

**Issue by se-ti** [marttiphpbb/phpbb-ext-jqueryuidatepicker#1]
**Fatal error:** Uncaught LogicException: Attribute "name" does not exist for Node "Twig_Node_Expression_Constant". 
in ..../phpBB3/vendor/twig/twig/lib/Twig/Node.php:155 

**Stack trace:** 
#0 ..../phpBB3/phpbb/template/twig/node/event.php(43): Twig_Node->getAttribute('name') 
#1 ..../phpBB3/vendor/twig/twig/lib/Twig/Node.php(117): phpbb\template\twig\node\event->compile(Object(Twig_Compiler)) 
#2 ..../phpBB3/vendor/twig/twig/lib/Twig/Compiler.php(98): Twig_Node->compile(Object(*Twig_Compiler)) 

**Context** 
print_r($this->getNode('expr')) @ .../twig/node/event.php(43) shows 
STYLESHEETS_6333caa08d8a9f10

Twig_Node_Expression_Constant Object ( 
    [nodes:protected] => Array ( ) 
    [attributes:protected] => Array ( [value] => marttiphpbb_jqueryuidatepicker ) 
    __[lineno:protected] => 14__ 
    [tag:protected] => 
    [name:Twig_Node:private] => __@marttiphpbb_jqueryuidatepicker/datepicker.html__ ) 

**Reproducing:** clean phpBB 3.2.2 installation
PHP 7.2.9
gentoo 4.4.26 (i don't think it's relevant).

This extension copied to ext/marttiphpbb.
ACP shows this extension ready to enable.
Attempt to enable results in white screen.
Turning on debug output shows stack and context;

**Comment by marttiphpbb** [comment]
Thanks, obviously the quotes shouldn't be there in the EVENT. It seems I forgot to upload the latest version. It should be corrected now.
